version: '3.8'
services:
  api:
    build: .
    ports:
      - 8000:8000
    # env_file:
    #     - .env
    environment:
      - DATABASE_HOSTNAME=postgres
      - DATABASE_PORT=5432
      - DATABASE_NAME=fastapi
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=postgres
      - SECRET_KEY=887524b0fc17c22bf43dfe850330fc34c76bc1c5ff5add5e37720ec4f072768f
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=120
    volumes:
      - ./:/usr/src/app:ro
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
networks:
  default:
    name: postgres
    external: true